import distutils.sysconfig

Import('env')

SWIGFLAGS = ['-c++',
	     '-python']

pyenv = env.Clone(SWIGFLAGS = SWIGFLAGS)

SWIGFLAGS = ['-c++',
	     '-python']

pyenv.SharedLibrary('_nfp.so',
		  ['nfp.i', Glob('../core/*.cpp'), Glob('../algos/*.cpp')],
		  CPPPATH=("/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6",
		           "/Library/Frameworks/QtCore.framework/Headers",
			   "../core",
			   "../algos"),
	          LIBS=('python2.6', 'QtCore', 'glog'),
		  LIBPATH="/Library/Frameworks/Python.framework/Versions/2.6/lib",
                  SHLIBPREFIX="")

