import distutils.sysconfig

env = Environment(SWIGFLAGS=['-c++ -python '.split()],
                  CPPPATH=("/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6",
		           "/Library/Frameworks/QtCore.framework/Headers",
			   "../core"),
	          LIBS=('python2.6', 'QtCore', 'glog'),
		  LIBPATH="/Library/Frameworks/Python.framework/Versions/2.6/lib",
                  SHLIBPREFIX="",
		  CPPFLAGS="-O3 -DNDEBUG -pipe -combine -ansi -Wall -fno-strict-aliasing")

env.SharedLibrary('_nfp.so',
		  ['nfp.i', Glob('../core/*.cpp')])
