#!/bin/sh

current_branch=$(git branch -l | grep -E '^\*' | cut -b 3-)

for i in $(git branch -l | cut -b 3- | grep -v -e next -e master)
do
  git rebase --onto next --root $i
done

git rebase --onto nf/import_export_shm_segments --root nf/import_export_shm_segments_in_c

git checkout $current_branch
