MODE = 'prod'

BASE_CPPFLAGS = ['-pipe',
            '-combine',
            '-ansi',
            '-Wall',
            '-fno-strict-aliasing']
ADD_CPPFLAGS = dict()
ADD_CPPFLAGS['prod'] = ['-O3',
                        '-DNDEBUG']
ADD_CPPFLAGS['test'] = ['-g',
                        '-pg',
                        '-fno-omit-frame-pointer',
                        '-fno-inline-functions',
                        '-fno-inline-functions-called-once',
                        '-fno-optimize-sibling-calls',
                        '-fno-default-inline',
                        '-fno-inline']

BASE_LINKFLAGS = []
ADD_LINKFLAGS = dict()
ADD_LINKFLAGS['prod'] = []
ADD_LINKFLAGS['test'] = ['-pg',]

Program("nfpshm",
        ("./nfpshm.cpp", Glob("../core/*.cpp"), Glob("../algos/*.cpp")),
        LIBS=('QtCore', 'glog'),
        CPPPATH=("/Library/Frameworks/QtCore.framework/Headers",
		 "../core",
		 "../algos"),
        CPPFLAGS = BASE_CPPFLAGS + ADD_CPPFLAGS[MODE],
	LINKFLAGS = BASE_LINKFLAGS + ADD_LINKFLAGS[MODE])

